#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GuidR.Droid.Resource", IsApplication=true)]

namespace GuidR.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060008
			public const int common_action_bar_splitter = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int common_google_signin_btn_text_dark = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_dark_default = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_dark_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_signin_btn_text_dark_focused = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark_pressed = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int common_google_signin_btn_text_light = 2131099666;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_signin_btn_text_light_default = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_light_disabled = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light_focused = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_signin_btn_text_light_pressed = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int common_plus_signin_btn_text_dark = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int common_plus_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_plus_signin_btn_text_dark_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_plus_signin_btn_text_dark_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_plus_signin_btn_text_dark_pressed = 2131099649;
			
			// aapt resource value: 0x7f060014
			public const int common_plus_signin_btn_text_light = 2131099668;
			
			// aapt resource value: 0x7f060004
			public const int common_plus_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_plus_signin_btn_text_light_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_plus_signin_btn_text_light_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_plus_signin_btn_text_light_pressed = 2131099653;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Animal_button_medium = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Animal_button_small = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Arrow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Arrow_small = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Baboon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BaboonHeader = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Black_kaiman = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Brown_bear = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int BrownBearHeader = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Californian_Sea_Lion = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Checkin_button_medium = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Checkin_button_small = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_full_open_on_phone = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_dark_disabled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_icon_dark_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_icon_dark_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_icon_dark_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_icon_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_icon_light_disabled = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_icon_light_focused = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_icon_light_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_icon_light_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_text_dark_disabled = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_text_dark_focused = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_text_dark_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_text_dark_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_google_signin_btn_text_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_google_signin_btn_text_light_disabled = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_google_signin_btn_text_light_focused = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_google_signin_btn_text_light_normal = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_google_signin_btn_text_light_pressed = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_ic_googleplayservices = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_icon_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_icon_dark_focused = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_icon_dark_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_icon_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_icon_light_disabled = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_icon_light_focused = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_icon_light_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_icon_light_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_plus_signin_btn_text_dark = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_plus_signin_btn_text_dark_disabled = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_plus_signin_btn_text_dark_focused = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_plus_signin_btn_text_dark_normal = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_plus_signin_btn_text_dark_pressed = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int common_plus_signin_btn_text_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int common_plus_signin_btn_text_light_disabled = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int common_plus_signin_btn_text_light_focused = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int common_plus_signin_btn_text_light_normal = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int common_plus_signin_btn_text_light_pressed = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Elephant = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ElephantHeader = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Emperor_tamarin = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Facilities_button_medium = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int Facilities_button_small = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int Giraffe = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int GiraffeHeader = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int HippoHeader = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int Icon = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int Info_button = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int Info_button_medium = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int Info_button_small = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int KaimanHeader = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int Lemur = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int LemurHeader = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int Lion = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int LionHeader = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int logo = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int Map_button_medium = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int Map_button_small = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int Map_pin = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int Meercat = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int MeercatHeader = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int News_button_medium = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int News_button_small = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int Penguin = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int PenguinHeader = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int placeholderButton = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int placeholderButtonMedium = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int Polar_bear = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int PolarBearHeader = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int Pygmy_Hippo = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int SeaLionHeader = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int splashScreen = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int SplashScreenBackground = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int SplashScreenImage = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int SquareButton = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int TamarinHeader = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int test = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int Tiger = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int TigerHeader = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int Toilet = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int Zebra = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int ZebraHeader = 2130837602;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080028
			public const int AboutAnimal = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int FeedingTimePanel = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int Feedingtime = 2131230762;
			
			// aapt resource value: 0x7f080025
			public const int HeaderImage = 2131230757;
			
			// aapt resource value: 0x7f080027
			public const int LatinName = 2131230759;
			
			// aapt resource value: 0x7f080026
			public const int Name = 2131230758;
			
			// aapt resource value: 0x7f080005
			public const int adjust_height = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int adjust_width = 2131230726;
			
			// aapt resource value: 0x7f080031
			public const int animalButton = 2131230769;
			
			// aapt resource value: 0x7f08000a
			public const int auto = 2131230730;
			
			// aapt resource value: 0x7f08000f
			public const int baboonButton = 2131230735;
			
			// aapt resource value: 0x7f080019
			public const int blackkaimanButton = 2131230745;
			
			// aapt resource value: 0x7f080010
			public const int brownbearButton = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int buttonPanel1 = 2131230734;
			
			// aapt resource value: 0x7f08002e
			public const int buttonPanel2 = 2131230766;
			
			// aapt resource value: 0x7f080011
			public const int buttonpanel2 = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int buttonpanel3 = 2131230740;
			
			// aapt resource value: 0x7f080017
			public const int buttonpanel4 = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int buttonpanel5 = 2131230746;
			
			// aapt resource value: 0x7f08001d
			public const int buttonpanel6 = 2131230749;
			
			// aapt resource value: 0x7f080020
			public const int buttonpanel7 = 2131230752;
			
			// aapt resource value: 0x7f080023
			public const int buttonpanel8 = 2131230755;
			
			// aapt resource value: 0x7f080035
			public const int checkinbutton = 2131230773;
			
			// aapt resource value: 0x7f08000b
			public const int dark = 2131230731;
			
			// aapt resource value: 0x7f080015
			public const int elephantButton = 2131230741;
			
			// aapt resource value: 0x7f08001b
			public const int emperorButton = 2131230747;
			
			// aapt resource value: 0x7f080032
			public const int facilityButton = 2131230770;
			
			// aapt resource value: 0x7f080016
			public const int giraffeButton = 2131230742;
			
			// aapt resource value: 0x7f080013
			public const int hippoButton = 2131230739;
			
			// aapt resource value: 0x7f080000
			public const int hybrid = 2131230720;
			
			// aapt resource value: 0x7f080007
			public const int icon_only = 2131230727;
			
			// aapt resource value: 0x7f08000d
			public const int imageView = 2131230733;
			
			// aapt resource value: 0x7f080033
			public const int infoButton = 2131230771;
			
			// aapt resource value: 0x7f08001c
			public const int lemurButton = 2131230748;
			
			// aapt resource value: 0x7f08000c
			public const int light = 2131230732;
			
			// aapt resource value: 0x7f08001e
			public const int lionButton = 2131230750;
			
			// aapt resource value: 0x7f080036
			public const int map = 2131230774;
			
			// aapt resource value: 0x7f08002b
			public const int mapButton = 2131230763;
			
			// aapt resource value: 0x7f080021
			public const int meercatButton = 2131230753;
			
			// aapt resource value: 0x7f080034
			public const int newsbutton = 2131230772;
			
			// aapt resource value: 0x7f080001
			public const int none = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int normal = 2131230722;
			
			// aapt resource value: 0x7f08001f
			public const int penguinButton = 2131230751;
			
			// aapt resource value: 0x7f080018
			public const int polarbearButton = 2131230744;
			
			// aapt resource value: 0x7f080003
			public const int satellite = 2131230723;
			
			// aapt resource value: 0x7f080012
			public const int sealionButton = 2131230738;
			
			// aapt resource value: 0x7f080008
			public const int standard = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int terrain = 2131230724;
			
			// aapt resource value: 0x7f080022
			public const int tigerButton = 2131230754;
			
			// aapt resource value: 0x7f08002c
			public const int toiletButton1 = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int toiletButton2 = 2131230765;
			
			// aapt resource value: 0x7f08002f
			public const int toiletButton3 = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int toiletButton4 = 2131230768;
			
			// aapt resource value: 0x7f080009
			public const int wide = 2131230729;
			
			// aapt resource value: 0x7f080024
			public const int zebraButton = 2131230756;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AnimalMenu = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AnimalPage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FacilitiesMenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Map = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04001f
			public const int app_name = 2130968607;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_api_unavailable_text = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_enable_text = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_enable_title = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_button = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_text_phone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_text_tablet = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_install_title = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_invalid_account_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_invalid_account_title = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_network_error_text = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_network_error_title = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_ticker = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_play_services_restricted_profile_text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_restricted_profile_title = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_sign_in_failed_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_sign_in_failed_title = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_unsupported_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_unsupported_title = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_update_button = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_title = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_updating_text = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_updating_title = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_wear_update_text = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int common_signin_button_text_long = 2130968606;
			
			// aapt resource value: 0x7f040020
			public const int google_maps_key = 2130968608;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int NoTitle_splash = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Theme_splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
