#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GuidR.Droid.Resource", IsApplication=true)]

namespace GuidR.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Animal_button_medium = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Animal_button_small = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Checkin_button_medium = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Checkin_button_small = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Facilities_button_medium = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Facilities_button_small = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Info_button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Info_button_medium = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Info_button_small = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int logo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Map_button_medium = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Map_button_small = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int News_button_medium = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int News_button_small = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int placeholderButton = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int placeholderButtonMedium = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int splashScreen = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int SplashScreenBackground = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int SplashScreenImage = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int SquareButton = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int test = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int animalButton = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int buttonPanel1 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int buttonpanel2 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int buttonpanel3 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int checkinbutton = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int facilityButton = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int imageView = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int infoButton = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int mapButton = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int newsbutton = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
